name: Linux
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  Ec2LinuxRun:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create build directory
        run: mkdir ${{github.workspace}}/build
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../
      - name: Run make
        working-directory: ${{github.workspace}}/build
        run: make -j 4
      - name: Run Test
        working-directory: ${{github.workspace}}/build
        run: ctest --no-compress-output --output-on-failure -T Test --build-config Release
